# v0.1

name: Deploy Theme to QA

on: 
  pull_request:
    types: [labeled]

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'deploy-qa')

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

    steps:
    - name: Create deploy step
      if: ${{ github.event_name == 'pull_request' }}
      uses: VirtoCommerce/vc-github-actions/create-deploy-pr@VDS-414
      with:
        artifactKey: "B2B_THEME_URL"
